# Pandas 한번에 제대로 배우기




---



In [ ]:
import numpy as np
import pandas as pd
pd.__version__


'1.0.5'

## Pandas 객체


### Series 객체

In [ ]:
s = pd.Series([0,0.25,0.5,0.75,1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [ ]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.index

# 벨류와 인덱스로 구성되어잇다

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s[1]

0.25

In [ ]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [ ]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
              index = ['a','b','c','d','e'])

s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['c']

0.5

In [ ]:
s[['c','d','e']]
#특 정 인덱스만 불러올수 있다

c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
'b' in s
# s 라는 시지르에 b라는 것이 있어?

True

In [ ]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
              index = [2,4,6,8,10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s[4]

0.25

In [ ]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s.unique()
# 유니크 한 값만 보내줍니다

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.isin([0.25,0.75])

#불리언 형태로 인덱스위치에 true로 반환

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [ ]:
pop_tuple = {'서울특별시': 9720846,
             '부산광역시': 3404423,
             '인천광역시': 2947217,
             '대구광역시': 2427954,
             '대전광역시': 1471040,
             '광주광역시': 1455048,}
        
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [ ]:
population['서울특별시']

9720846

In [ ]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

In [ ]:
pd.DataFrame([{'a':2,'b':4,'d':3},{'a':4,'b':5,'c':7}])

#중복된 missing values를 nan이라 표현


a  b    d    c
0  2  4  3.0  NaN
1  4  5  NaN  7.0

### DataFrame 객체

In [ ]:
pd.DataFrame([{'a':2,'b':4,'d':3},{'a':4,'b':5,'c':7}])

#중복된 missing values를 nan이라 표현


a  b    d    c
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [ ]:
pd.DataFrame(np.random.rand(5,5),
             columns = ['a','b','c','d','e'],
             index = [1,2,3,4,5])


a         b         c         d         e
1  0.308145  0.904408  0.085807  0.166740  0.184766
2  0.610827  0.842072  0.834969  0.824865  0.360238
3  0.218393  0.589524  0.215802  0.931943  0.301092
4  0.075455  0.790592  0.090804  0.493065  0.061305
5  0.778081  0.828606  0.387061  0.047276  0.606053

In [ ]:
male_tuple = {'서울특별시': 4732275,
             '부산광역시': 1668618,
             '인천광역시': 1476813,
             '대구광역시': 1198815,
             '대전광역시': 734441,
             '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [ ]:
female_tuple ={'서울특별시': 4988571,
             '부산광역시': 1735805,
             '인천광역시': 1470404,
             '대구광역시': 1229139,
             '대전광역시': 736599,
             '광주광역시': 734988}

female = pd.Series(female_tuple)  
female      

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [ ]:
korea_df = pd.DataFrame({'인구수': population,
                        '남자인구수' : male,
                        '여자인구수' : female})
korea_df

#하나의 시리즈 끼리 결합이되어 데이터 프레임이 된다
# 다 index는 공통으로 가지고잇네?

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [ ]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [ ]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['서울특별시':'부산광역시']
#한개만 불러오는건 안되는건가?

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805

### Index 객체


In [ ]:
# index
# int64index
# multiindex
# dtatimeindex
# periodindex

In [ ]:
idx = pd.Index([2,4,6,8,10])
idx

#이건 또 대문자만 가능하는군
#정수값만 넣어주었으니 int64로 되는군


Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [ ]:
idx[4]

10

In [ ]:
idx[1:2]

Int64Index([4], dtype='int64')

In [ ]:
idx[-1::-1]
# a = [1,2,3,4,5]
# a[-1::-1]


Int64Index([10, 8, 6, 4, 2], dtype='int64')

In [ ]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [ ]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [ ]:
# append
# difference
# intersection
# union
# isin
# delete
# drop
# insert
# in_monotonic
# os_unique
# unique

In [ ]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))

#append 사용 가능 
#list처럼 중복되는 것도 그냥 쭉 써줌


Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')


In [ ]:
print(idx1.difference(idx2))
print(idx1 - idx2)
#차집합
#배열의 개념이야

Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')


In [ ]:
print(idx1.intersection(idx2))
print(idx1 & idx2)

Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')


In [ ]:
print(idx1.union(idx2))
print(idx1 | idx2)
# union은 중복 안된 형태로 
# 합집합이지

Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')


In [ ]:
print(idx1.delete(0))

# 인덱스 위치로 빠지게 한거고
# 맨 처음 값이 빠짐

print(idx1.drop(6))

#지정된 값을 빼줌

Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 2, 4, 8], dtype='int64')


In [ ]:
print(idx1 ^ idx2)
#공통된 나머지를 뺌

Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [ ]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
              index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['b']

0.25

In [ ]:
'b' in s

True

In [ ]:
s.values

#series는 values값은 ( ) 안붙이네

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.keys()

#series는 keys 갑들은 ( ) 붙이고

<bound method Series.keys of a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64>

In [ ]:
list(s.items())
#zip 형태로 list로 한번 묶어 줘야 한데

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [ ]:
s['f'] = 1.25
s
# 특정 값을 집어 넣을수 잇어

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [ ]:
s['a':'d']
# 슬라이싱을 통해 지정해서 꺼낼수 이슴

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[0:4]
#똑같이 인덱스로 호출 가능

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[(s > 0.4) & (s < 0.8)]

# s의 values들에게 조건문을 넣을수도 있구나

c    0.50
d    0.75
dtype: float64

In [ ]:
s[['a','c','b']]

#순서를 바꾼채로 원하는 것만 뽑을수 있음
#대신 list로 뽑아야함

a    0.00
c    0.50
b    0.25
dtype: float64

### Series 인덱싱

In [ ]:
s = pd.Series(['a','b','c','d','e'],
              index = [1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [ ]:
s[1]

'a'

In [ ]:
s[2:4]

5    c
7    d
dtype: object

In [ ]:
s.iloc[2:4]
#우리가 알고있는 진짜 인덱스로

5    c
7    d
dtype: object

In [ ]:
s.reindex(range(10))

#기존을 새로운 인덱스로 바꿔줘

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [ ]:
s.reindex(range(10),method = 'bfill')

#non값들을 이전값들로 채워줘!!
#method를 이용하자!

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [ ]:
# df[val]
# df.loc[val]
# df. loc[:,val]
# df.loc[va1,val2]
# df.iloc[where]
# df,iloc:,where]
# df.iloc[where_1,where_2]
# df.at[label_1,label_2]
# df.iat[i,j]
# reindex
# get_value, set_value

In [ ]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.남자인구수

# .으로도 가져올수 있구만!

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['남여비율'] = (korea_df['남자인구수']*100 / korea_df['여자인구수'])

#k에 대한 곱은 행렬과 같은데
# 행렬 나누기 행렬은 같은 인덱스로만 나눠지나?

In [ ]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [ ]:
korea_df.values
#값들만 추출 가능

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [ ]:
korea_df.T

서울특별시         부산광역시  ...         대전광역시         광주광역시
인구수    9.720846e+06  3.404423e+06  ...  1.471040e+06  1.455048e+06
남자인구수  4.732275e+06  1.668618e+06  ...  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  ...  7.365990e+05  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  ...  9.970703e+01  9.796895e+01

[4 rows x 6 columns]

In [ ]:
korea_df.values[0:3]
#한 행만 가져올수 있음
# 표의 인덱스로 접간 가능

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02]])

In [ ]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [ ]:
korea_df.loc[:'인천광역시',:'남자인구수']

#loc을 통해 [row,columns]
            # [열,행]을 뽑을수 잇음

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [ ]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [ ]:
korea_df.loc[(korea_df.인구수 <2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [ ]:
korea_df.loc[(korea_df.인구수 >2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [ ]:
korea_df.loc[(korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [ ]:
korea_df.loc[:,'인구수':'여자인구수']
# korea_df.loc[:,korea_df.values[0]:korea_df.values[2]]

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df.loc[(korea_df.인구수 >2500000) & (korea_df.남여비율 > 100)]

#labels 인 이름으로 접근해도 되고

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [ ]:
korea_df.iloc[:3,:2]

#iloc로 접근 해도 되고
#이게 나한테 익숙하다
# 이게 인덱스지

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [ ]:
# 1차원의 series와 2차원의 dataframe 객체를 넘어
# 3차원, 4차원 이상의 고차원데이터 처리
# 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

In [ ]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [ ]:
idx_tuples = [('서울특별시', 2010),('서울특별시',2020),
              ('부산광역시', 2010),('부산광역시',2020),
              ('인천광역시', 2010),('인천광역시',2020),
              ('대구광역시', 2010),('대구광역시',2020),
              ('대전광역시', 2010),('대전광역시',2020),
              ('광주특별시', 2010),('광주특별시',2020)]

idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주특별시', 2010),
 ('광주특별시', 2020)]

In [ ]:
pop_tuples = [10321545, 9720846,
              3567910, 3404423,
              2758296, 2947217,
              2511676,2427954,
              1503664, 1471040,
              1454636, 1455048]

population = pd.Series(pop_tuples, index = idx_tuples)
population

(서울특별시, 2010)    10321545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     3567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주특별시, 2010)     1454636
(광주특별시, 2020)     1455048
dtype: int64

In [ ]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

# 멀티 인덱스로 구성 해줌

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주특별시', 2010),
            ('광주특별시', 2020)],
           )

In [ ]:
population = population.reindex(midx)
population

# 멀티인덱싱 함수 쓰고 리인덱싱 쓰먄 가능

서울특별시  2010    10321545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주특별시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population [:, 2010]

# 2010 년도까지 슬라이싱 인덱스 사용 가능

서울특별시    10321545
부산광역시     3567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주특별시     1454636
dtype: int64

In [ ]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [ ]:
korea_mdf = population.unstack()
korea_mdf
# unstack()
# series를 
# 전형적인 dataframe으로 만들어줌

2010     2020
광주특별시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   3567910  3404423
서울특별시  10321545  9720846
인천광역시   2758296  2947217

In [ ]:
korea_mdf.stack()

# stack()
# 다시 다중 인덱싱을 가진 series로 바꿔줌

광주특별시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     3567910
       2020     3404423
서울특별시  2010    10321545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [ ]:
korea_df['인구수'][0].unstack()

AttributeError: ignored

In [ ]:
male_tuples = [5111259, 4732275,
               1773170, 1668618,
               1390356, 1476813,
               1255245, 1198815,
               753648, 734441,
               721780, 720060]

male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples})

korea_mdf

총인구수    남자인구수
서울특별시 2010  10321545  5111259
      2020   9720846  4732275
부산광역시 2010   3567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주특별시 2010   1454636   721780
      2020   1455048   720060

In [ ]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]

female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                         '여자인구수':female_tuples})

korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10321545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   3567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주특별시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [ ]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주특별시  2010     98.488653
       2020     97.968946
dtype: float64

In [ ]:
ratio.unstack()

2010        2020
광주특별시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                         '여자인구수':female_tuples,
                          '남녀비율':ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10321545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주특별시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [ ]:
df = pd.DataFrame(np.random.rand(6,3),
                  index = [['a','a','b','b','c','c'],[1,2,1,2,1,2,]],
                  columns = ['c1','c2','c3'])

df

#만들때 겹쳐놓게 써놓으면 표현 가능

c1        c2        c3
a 1  0.261891  0.258584  0.098044
  2  0.489938  0.912279  0.104384
b 1  0.397148  0.689445  0.067931
  2  0.323468  0.209189  0.959589
c 1  0.473735  0.516197  0.428847
  2  0.107236  0.379492  0.513114

In [ ]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'],[1,2,1,2,1,2]])

# 자동으로 멀티 인덱스로 만들수잇음

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_arrays([('a',1),('a',2),('b',2),('c',1),('c',2)])

MultiIndex([('a', 'a', 'b', 'c', 'c'),
            (  1,   2,   2,   1,   2)],
           )

In [ ]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])


#이게 가장 무난 하네 
#각 index마다 따른 이름 넣는 게 아니면

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels = [['a','b','c'],[1,2]],
              codes = [[0,0,1,1,2,2],[0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
population

서울특별시  2010    10321545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주특별시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population.index.names = ['행정구역','년도']
population

#인덱스에도 이름을 붙일수가 있구만

행정구역   년도  
서울특별시  2010    10321545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주특별시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population.unstack()

년도         2010     2020
행정구역                    
광주특별시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   3567910  3404423
서울특별시  10321545  9720846
인천광역시   2758296  2947217

In [ ]:
idx = pd.MultiIndex.from_product([['a','b','c'],[1,2]],
                                 names=['1','2'])
cols = pd.MultiIndex.from_product([['c1','c2','c3'],[1,2]],
                                  names = ['col_names1','col_name2'])
data = np.round(np.random.randn(6,6),2)
mdf = pd.DataFrame(data, index = idx ,columns=cols)
mdf

col_names1    c1          c2          c3      
col_name2      1     2     1     2     1     2
1 2                                           
a 1        -0.23  0.21  1.71 -0.83  0.69 -0.51
  2         0.45  0.99  0.72 -0.22  0.32 -0.31
b 1         2.26  0.31  0.56 -0.63  0.73 -0.18
  2         1.07 -0.16  0.13 -1.24 -0.05  0.84
c 1        -0.06 -0.27 -0.16 -2.30  0.47  0.97
  2         0.62  1.81  0.43  0.48  0.87 -1.42

In [ ]:
mdf['c2']

col_name2     1     2
1 2                  
a 1        1.71 -0.83
  2        0.72 -0.22
b 1        0.56 -0.63
  2        0.13 -1.24
c 1       -0.16 -2.30
  2        0.43  0.48

#### 인덱싱 및 슬라이싱

In [ ]:
population

행정구역   년도  
서울특별시  2010    10321545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주특별시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population['인천광역시',2010]

2758296

In [ ]:
population[: ,2010]

행정구역
서울특별시    10321545
부산광역시     3567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주특별시     1454636
dtype: int64

In [ ]:
population[population > 3000000].unstack()

년도         2010     2020
행정구역                    
서울특별시  10321545  9720846
부산광역시   3567910  3404423

In [ ]:
population[['대구광역시','대전광역시']].unstack()

# 원하는 걸 고를땐 list로 입력!!

년도        2010     2020
행정구역                   
대구광역시  2511676  2427954
대전광역시  1503664  1471040

In [ ]:
mdf

col_names1    c1          c2          c3      
col_name2      1     2     1     2     1     2
1 2                                           
a 1        -0.23  0.21  1.71 -0.83  0.69 -0.51
  2         0.45  0.99  0.72 -0.22  0.32 -0.31
b 1         2.26  0.31  0.56 -0.63  0.73 -0.18
  2         1.07 -0.16  0.13 -1.24 -0.05  0.84
c 1        -0.06 -0.27 -0.16 -2.30  0.47  0.97
  2         0.62  1.81  0.43  0.48  0.87 -1.42

In [ ]:
mdf['c2',1].unstack()

#column 2의 1만 불러내기

2     1     2
1            
a  1.71  0.72
b  0.56  0.13
c -0.16  0.43

In [ ]:
mdf.iloc[:3,:4]

col_names1    c1          c2      
col_name2      1     2     1     2
1 2                               
a 1        -0.23  0.21  1.71 -0.83
  2         0.45  0.99  0.72 -0.22
b 1         2.26  0.31  0.56 -0.63

In [ ]:
mdf.loc[:,('c2',1)]

# columns c2의 1번째것만 해줘

1  2
a  1    1.71
   2    0.72
b  1    0.56
   2    0.13
c  1   -0.16
   2    0.43
Name: (c2, 1), dtype: float64

In [ ]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:,2], idx_slice[:,2]]


col_names1    c1    c2    c3
col_name2      2     2     2
1 2                         
a 2         0.99 -0.22 -0.31
b 2        -0.16 -1.24  0.84
c 2         1.81  0.48 -1.42

#### 다중 인덱스 재정렬

In [ ]:
idx
#멀티 인덱스 개체

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['1', '2'])

In [ ]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10321545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주특별시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [ ]:
# korea_mdf['서울특별시':'인천광역시']
#정렬이 안되어있기에 오류가 남

korea_mdf = korea_mdf.sort_index()
korea_mdf

#가나다 순으로 sort가 되어서
# 슬라이싱이가능해짐

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주특별시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10321545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf['서울특별시':'인천광역시']

#sort 한 후를 기준으로 index나 slicing을 해야한다

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10321545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf.unstack(level = 0)

#level에 따라 a라인과 b라인을 바꿀수 있다

총인구수                    ...       남녀비율                       
행정구역    광주특별시    대구광역시    대전광역시  ...      부산광역시      서울특별시       인천광역시
년도                               ...                                  
2010  1454636  2511676  1503664  ...  98.798155  98.269140  101.638668
2020  1455048  2427954  1471040  ...  96.129346  94.862336  100.435867

[2 rows x 24 columns]

In [ ]:
korea_mdf.unstack(level = 1)

총인구수             남자인구수  ...    여자인구수        남녀비율            
년도         2010     2020     2010  ...     2020        2010        2020
행정구역                               ...                                 
광주특별시   1454636  1455048   721780  ...   734988   98.488653   97.968946
대구광역시   2511676  2427954  1255245  ...  1229139   99.905606   97.532907
대전광역시   1503664  1471040   753648  ...   736599  100.484256   99.707032
부산광역시   3567910  3404423  1773170  ...  1735805   98.798155   96.129346
서울특별시  10321545  9720846  5111259  ...  4988571   98.269140   94.862336
인천광역시   2758296  2947217  1390356  ...  1470404  101.638668  100.435867

[6 rows x 8 columns]

In [ ]:
korea_mdf.unstack(level = 2)

In [ ]:
korea_mdf.stack()

행정구역   년도         
광주특별시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남녀비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남녀비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남녀비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남녀비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남녀비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남녀비율     9.970703e+01
부산광역시  2010  총인구수     3.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남녀비율     9.879815e+01
 

In [ ]:
korea_mdf
# 다시 정상적으로 돌아옴

# 행정구역과 년도는 살아 있음

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주특별시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10321545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level = 0)
idx_flat

#e다 flat 한 형태로 들어갔네
#원래는 2칸에 한 지역씩 들어갔는데

# 행정구역 사라졋네

행정구역      총인구수    남자인구수    여자인구수        남녀비율
년도                                                 
2010  광주특별시   1454636   721780   732856   98.488653
2020  광주특별시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   3567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10321545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

#행정구역과 년도 둘다 사라졌구만

#둘다 결국 table 구조로 들어갔네

행정구역    년도      총인구수    남자인구수    여자인구수        남녀비율
0   광주특별시  2010   1454636   721780   732856   98.488653
1   광주특별시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   3567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10321545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat.set_index(['행정구역','년도'])

#다시 인덱스를 만들고 싶다면..

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주특별시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10321545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [ ]:
s = pd.Series(np.random.randint(0,10,5))

In [ ]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)),
                  columns = ['a','b','c'])



df

a  b  c
0  3  5  0
1  7  6  0
2  6  7  9

In [ ]:
 np.exp(s)

0    1096.633158
1       2.718282
2       2.718282
3      54.598150
4    1096.633158
dtype: float64

In [ ]:
np.cos(df * np.pi / 4)

a             b         c
0 -7.071068e-01 -7.071068e-01  1.000000
1  7.071068e-01 -1.836970e-16  1.000000
2 -1.836970e-16  7.071068e-01  0.707107

In [ ]:
s1 = pd.Series([1,3,5,7,9], index = [0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10], index = [1,2,3,4,5])
s1+s2

#인덱스 기준으로 서로 합쳐준다
#따라서 6열이 만들어지고 
# 그중 1열,6열은 nan이 되네 s1에 값이 있어도

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value = 0)


# nan값이 아니지.. nan이 안나오도록 
# 서로 부족한 부분을 fill_value를 통해 가변변수로 만들어주고
# 그걸 더해주는 거지

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0,20,(3,3)),
                   columns = list('ACD'))
df1

A   C  D
0  8   6  9
1  0  14  1
2  7  11  6

In [ ]:
list('하늘을 우러러')
# '하늘을 우러러'.split()

['하', '늘', '을', ' ', '우', '러', '러']

In [ ]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),
                   columns = list('BAECD'))
df2

B   A   E   C   D
0  15  15   5   3   9
1  13  18   5  10   0
2  19  15  16  18   1
3   4   1  18  19   8
4  14  15  14   5  11

In [ ]:
df1+df2

# 해당하는 인덱스의 교집합만 계산이 됨

A   B     C     D   E
0  23.0 NaN   9.0  18.0 NaN
1  18.0 NaN  24.0   1.0 NaN
2  22.0 NaN  29.0   7.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
# 이 빈 부분을 어떻게 채울까

fvalue = df1.stack().mean()

# stack으로 mean 값을 구할수 있다
df1.add(df2, fill_value = fvalue)

A          B          C          D          E
0  23.000000  21.888889   9.000000  18.000000  11.888889
1  18.000000  19.888889  24.000000   1.000000  11.888889
2  22.000000  25.888889  29.000000   7.000000  22.888889
3   7.888889  10.888889  25.888889  14.888889  24.888889
4  21.888889  20.888889  11.888889  17.888889  20.888889

### 연산자 범용 함수


#### add()

In [ ]:
import numpy as np
import pandas as pd

a = np.random.randint(1,10,(3,3))
a

array([[1, 4, 3],
       [4, 3, 2],
       [9, 9, 4]])

In [ ]:
a +a[0]

#브뤗케스팅

array([[ 2,  8,  6],
       [ 5,  7,  5],
       [10, 13,  7]])

In [ ]:
df = pd.DataFrame(a,columns = list('abc'))
df

a  b  c
0  1  4  3
1  4  3  2
2  9  9  4

In [ ]:
df + df.iloc[0]

#위랑 똑같아 단지 dataframe을 씌워준거지

a   b  c
0   2   8  6
1   5   7  5
2  10  13  7

In [ ]:
df.add(df.iloc[0])

a   b  c
0   2   8  6
1   5   7  5
2  10  13  7

#### sub() / subtract()

In [ ]:
a

array([[1, 4, 3],
       [4, 3, 2],
       [9, 9, 4]])

In [ ]:
a - a[0]
#브뤗 캐스팅

array([[ 0,  0,  0],
       [ 3, -1, -1],
       [ 8,  5,  1]])

In [ ]:
df - df.iloc[0]

# 똑같아 브륏 케스팅이야

a  b  c
0  0  0  0
1  3 -1 -1
2  8  5  1

In [ ]:
df.sub(df.iloc[0])

a  b  c
0  0  0  0
1  3 -1 -1
2  8  5  1

In [ ]:
df.subtract(df['b'],axis=0)

#한 축으로
#브뤗캐스팅

a  b  c
0 -3  0 -1
1  1  0 -1
2  0  0 -5

In [ ]:
a

array([[1, 4, 3],
       [4, 3, 2],
       [9, 9, 4]])

#### mul() / multply()




In [ ]:
a

array([[1, 4, 3],
       [4, 3, 2],
       [9, 9, 4]])

In [ ]:
a*a[0]

array([[ 1, 16,  9],
       [ 4, 12,  6],
       [ 9, 36, 12]])

In [ ]:
df

a  b  c
0  1  4  3
1  4  3  2
2  9  9  4

In [ ]:
df * df.iloc[1]

a   b  c
0   4  12  6
1  16   9  4
2  36  27  8

In [ ]:
df.mul(df.iloc[1])

a   b  c
0   4  12  6
1  16   9  4
2  36  27  8

In [ ]:
df.multiply(df.iloc[2])

a   b   c
0   9  36  12
1  36  27   8
2  81  81  16

#### truediv() /  div() / divide() / floordiv()

In [ ]:
a

array([[1, 4, 3],
       [4, 3, 2],
       [9, 9, 4]])

In [ ]:
a/a[0]

array([[1.        , 1.        , 1.        ],
       [4.        , 0.75      , 0.66666667],
       [9.        , 2.25      , 1.33333333]])

In [ ]:
df/df.iloc[0]

a     b         c
0  1.0  1.00  1.000000
1  4.0  0.75  0.666667
2  9.0  2.25  1.333333

In [ ]:
df.truediv(df.iloc[0])

a     b         c
0  1.0  1.00  1.000000
1  4.0  0.75  0.666667
2  9.0  2.25  1.333333

In [ ]:
df.divide(df.iloc[2])

a         b     c
0  0.111111  0.444444  0.75
1  0.444444  0.333333  0.50
2  1.000000  1.000000  1.00

In [ ]:
a // a[0]

array([[1, 1, 1],
       [4, 0, 0],
       [9, 2, 1]])

In [ ]:
df.floordiv(df.iloc[0])

a  b  c
0  1  1  1
1  4  0  0
2  9  2  1

#### mod()

In [ ]:
a

array([[1, 4, 3],
       [4, 3, 2],
       [9, 9, 4]])

In [ ]:
a % a[0]

array([[0, 0, 0],
       [0, 3, 2],
       [0, 1, 1]])

In [ ]:
df

a  b  c
0  1  4  3
1  4  3  2
2  9  9  4

In [ ]:
df.mod(df.iloc[0])

a  b  c
0  0  0  0
1  0  3  2
2  0  1  1

#### pow()

In [ ]:
df ** df.iloc[0]

a     b   c
0  1   256  27
1  4    81   8
2  9  6561  64

In [ ]:
df.pow(df.iloc[0])

a     b   c
0  1   256  27
1  4    81   8
2  9  6561  64

In [ ]:
df

a  b  c
0  1  4  3
1  4  3  2
2  9  9  4

In [ ]:
row = df.iloc[0, ::2]
row

a    1
c    3
Name: 0, dtype: int64

In [ ]:
df -row

#선택한 부분만 빼기

a   b    c
0  0.0 NaN  0.0
1  3.0 NaN -1.0
2  8.0 NaN  1.0

### 정렬(Sort)

In [ ]:
s = pd.Series(range(5), index = list('abhjt'))
s

a    0
b    1
h    2
j    3
t    4
dtype: int64

In [ ]:
s.sort_index()

a    0
b    1
h    2
j    3
t    4
dtype: int64

In [ ]:
s.sort_values()

a    0
b    1
h    2
j    3
t    4
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0,4,(4,4)),
                  index = [2,4,1,3],columns = list('bfac'))
df

b  f  a  c
2  3  2  2  3
4  1  2  0  1
1  0  0  1  3
3  0  1  1  1

In [ ]:
df.sort_index()

b  f  a  c
1  0  0  1  3
2  3  2  2  3
3  0  1  1  1
4  1  2  0  1

In [ ]:
df.sort_values(by = 'b')

b  f  a  c
1  0  0  1  3
3  0  1  1  1
4  1  2  0  1
2  3  2  2  3

In [ ]:
df.sort_values(by=['a'])

b  f  a  c
4  1  2  0  1
1  0  0  1  3
3  0  1  1  1
2  3  2  2  3

In [ ]:
df

b  f  a  c
2  3  2  2  3
4  1  2  0  1
1  0  0  1  3
3  0  1  1  1

In [ ]:
df.sort_index(axis = 1)

a  b  c  f
2  2  3  3  2
4  0  1  1  2
1  1  0  3  0
3  1  0  1  1

### 순위(Ranking)


In [ ]:
average
min
max
first
dense

In [ ]:
s = pd.Series([-2,4,6,5,-4,6,0,2])
s

0   -2
1    4
2    6
3    5
4   -4
5    6
6    0
7    2
dtype: int64

In [ ]:
s.rank()

#그 값들중 순위를 매김

0    2.0
1    5.0
2    7.5
3    6.0
4    1.0
5    7.5
6    3.0
7    4.0
dtype: float64

In [ ]:
s.rank(method='first')

#중복된 값이 있으면 먼저 있는값이 먼저

0    2.0
1    5.0
2    7.0
3    6.0
4    1.0
5    8.0
6    3.0
7    4.0
dtype: float64

In [ ]:
s.rank(method = 'max')

0    2.0
1    5.0
2    8.0
3    6.0
4    1.0
5    8.0
6    3.0
7    4.0
dtype: float64

### 고성능 연산

In [ ]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows,ncols)) for i in range(4))

In [ ]:
%timeit df1 +df2 +df3+ df4

10 loops, best of 3: 60.5 ms per loop


In [ ]:
%timeit pd.eval('df1 +df2 +df3+df4')

# 문자열로 써야함
# 그리고 더 빠름

10 loops, best of 3: 40.8 ms per loop


In [ ]:
%timeit df1* -df2 / (-df3 * df4)

10 loops, best of 3: 92.9 ms per loop


In [ ]:
%timeit pd.eval('df1* -df2 / (-df3 * df4)')

10 loops, best of 3: 52 ms per loop


In [ ]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

1 loop, best of 3: 235 ms per loop


In [ ]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

10 loops, best of 3: 91.6 ms per loop


In [ ]:
pd.eval('df +df.iloc[0]')

b  f  a  c
2  6  4  4  6
4  4  4  2  4
1  3  2  3  6
3  3  3  3  4

In [ ]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns = list('abcde'))
df.head()

a         b         c         d         e
0  0.127918  0.590965  0.915602  0.653748  0.005872
1  0.409340  0.550621  0.817162  0.274976  0.605800
2  0.307070  0.315719  0.830663  0.758575  0.614265
3  0.291804  0.702215  0.853838  0.970240  0.843183
4  0.047992  0.449080  0.073480  0.929219  0.071338

In [ ]:
%timeit df['a']+ df['b']/df['c']-df['d']*df['e']

100 loops, best of 3: 13.4 ms per loop


In [ ]:
%timeit pd.eval('df.a +df.b / df.c - df.d * df.e')

100 loops, best of 3: 7.44 ms per loop


In [ ]:
%timeit df.eval('a + b /c - d * e')

100 loops, best of 3: 11.7 ms per loop


In [ ]:
df.eval('r =a +b /c -d *e',inplace =True)

# 계산된 결과값을 저장해 반영할수 있다
df.head()

a         b         c         d         e         r
0  0.127918  0.590965  0.915602  0.653748  0.005872  0.769518
1  0.409340  0.550621  0.817162  0.274976  0.605800  0.916580
2  0.307070  0.315719  0.830663  0.758575  0.614265  0.221184
3  0.291804  0.702215  0.853838  0.970240  0.843183  0.296135
4  0.047992  0.449080  0.073480  0.929219  0.071338  6.093301

In [ ]:
col_mean = df.mean(1)
# col_mean
df['a']+ col_mean

0         0.638521
1         1.005086
2         0.814982
3         0.951373
4         1.325394
            ...   
999995    1.578225
999996    1.192322
999997    0.915389
999998    1.392622
999999    0.914371
Length: 1000000, dtype: float64

In [ ]:
df.eval('a+@col_mean')

# @을 붙이면 외부값을 가져올수 있음

0         0.638521
1         1.005086
2         0.814982
3         0.951373
4         1.325394
            ...   
999995    1.578225
999996    1.192322
999997    0.915389
999998    1.392622
999999    0.914371
Length: 1000000, dtype: float64

In [ ]:
df[(df.a < 0.5) & (df.b <0.5) & (df.c> 0.5)]

a         b         c         d         e         r
2       0.307070  0.315719  0.830663  0.758575  0.614265  0.221184
8       0.329304  0.302040  0.622204  0.805464  0.435575  0.463900
13      0.478512  0.347777  0.713401  0.475524  0.345602  0.801661
27      0.478675  0.208200  0.600863  0.102135  0.120014  0.812920
30      0.375455  0.412300  0.865869  0.207066  0.460755  0.756217
...          ...       ...       ...       ...       ...       ...
999959  0.398758  0.141264  0.841000  0.816879  0.988740 -0.240952
999970  0.262527  0.291976  0.978739  0.199030  0.632978  0.434864
999981  0.171374  0.004080  0.659529  0.661669  0.135580  0.087851
999985  0.319256  0.129619  0.513172  0.177717  0.484811  0.485680
999999  0.465801  0.205988  0.968387  0.240682  0.173903  0.636658

[124868 rows x 6 columns]

In [ ]:
pd.eval('df[(df.a < 0.5) & (df.b <0.5) & (df.c> 0.5)]')

a         b         c         d         e         r
2       0.307070  0.315719  0.830663  0.758575  0.614265  0.221184
8       0.329304  0.302040  0.622204  0.805464  0.435575  0.463900
13      0.478512  0.347777  0.713401  0.475524  0.345602  0.801661
27      0.478675  0.208200  0.600863  0.102135  0.120014  0.812920
30      0.375455  0.412300  0.865869  0.207066  0.460755  0.756217
...          ...       ...       ...       ...       ...       ...
999959  0.398758  0.141264  0.841000  0.816879  0.988740 -0.240952
999970  0.262527  0.291976  0.978739  0.199030  0.632978  0.434864
999981  0.171374  0.004080  0.659529  0.661669  0.135580  0.087851
999985  0.319256  0.129619  0.513172  0.177717  0.484811  0.485680
999999  0.465801  0.205988  0.968387  0.240682  0.173903  0.636658

[124868 rows x 6 columns]

In [ ]:
# df 접근 안하고 바로 사용 하는법
df.query('(a < 0.5) and (b <0.5) and (c> 0.5)')

# 이건 계산이 아니라 조건문이기에 query를 씀 eval을 쓰지 않고

a         b         c         d         e         r
2       0.307070  0.315719  0.830663  0.758575  0.614265  0.221184
8       0.329304  0.302040  0.622204  0.805464  0.435575  0.463900
13      0.478512  0.347777  0.713401  0.475524  0.345602  0.801661
27      0.478675  0.208200  0.600863  0.102135  0.120014  0.812920
30      0.375455  0.412300  0.865869  0.207066  0.460755  0.756217
...          ...       ...       ...       ...       ...       ...
999959  0.398758  0.141264  0.841000  0.816879  0.988740 -0.240952
999970  0.262527  0.291976  0.978739  0.199030  0.632978  0.434864
999981  0.171374  0.004080  0.659529  0.661669  0.135580  0.087851
999985  0.319256  0.129619  0.513172  0.177717  0.484811  0.485680
999999  0.465801  0.205988  0.968387  0.240682  0.173903  0.636658

[124868 rows x 6 columns]

In [ ]:
col_mean = df['d'].mean()
df[(df.a < col_mean) & (df.b < col_mean)]
# 조건문과 따로 불러오고 싶은 행렬은 list형태로 시작

a         b         c         d         e         r
2       0.307070  0.315719  0.830663  0.758575  0.614265  0.221184
4       0.047992  0.449080  0.073480  0.929219  0.071338  6.093301
7       0.361112  0.361533  0.327670  0.815901  0.097566  1.384853
8       0.329304  0.302040  0.622204  0.805464  0.435575  0.463900
13      0.478512  0.347777  0.713401  0.475524  0.345602  0.801661
...          ...       ...       ...       ...       ...       ...
999976  0.070358  0.478852  0.251853  0.285398  0.548951  1.815002
999981  0.171374  0.004080  0.659529  0.661669  0.135580  0.087851
999985  0.319256  0.129619  0.513172  0.177717  0.484811  0.485680
999986  0.436090  0.219437  0.196812  0.113286  0.903340  1.448711
999999  0.465801  0.205988  0.968387  0.240682  0.173903  0.636658

[250060 rows x 6 columns]

In [ ]:
df.query('a < @col_mean and b <@col_mean')
#외부조건을 가져올땐 @를 쓰기

a         b         c         d         e         r
2       0.307070  0.315719  0.830663  0.758575  0.614265  0.221184
4       0.047992  0.449080  0.073480  0.929219  0.071338  6.093301
7       0.361112  0.361533  0.327670  0.815901  0.097566  1.384853
8       0.329304  0.302040  0.622204  0.805464  0.435575  0.463900
13      0.478512  0.347777  0.713401  0.475524  0.345602  0.801661
...          ...       ...       ...       ...       ...       ...
999976  0.070358  0.478852  0.251853  0.285398  0.548951  1.815002
999981  0.171374  0.004080  0.659529  0.661669  0.135580  0.087851
999985  0.319256  0.129619  0.513172  0.177717  0.484811  0.485680
999986  0.436090  0.219437  0.196812  0.113286  0.903340  1.448711
999999  0.465801  0.205988  0.968387  0.240682  0.173903  0.636658

[250060 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [ ]:
s1 = pd.Series(['a', 'b'], index = [1,2])
s2 = pd.Series(['c', 'd'], index = [3,4])
pd.concat([s1,s2])

1    a
2    b
3    c
4    d
dtype: object

In [ ]:
def create_df(cols,idx):
    data = {c : [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, idx)

In [ ]:
df1 = create_df('ab',[1,2])
df1

a   b
1  a1  b1
2  a2  b2

In [ ]:
df2 = create_df('ab',[3,4])
df2

a   b
3  a3  b3
4  a4  b4

In [ ]:
pd.concat([df1,df2])

a   b
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [ ]:
df3 = create_df('ab',[0,1])

In [ ]:
df4 = create_df('cd',[0,1])
df4

c   d
0  c0  d0
1  c1  d1

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly