# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [3]:
import numpy as np
np.__version__

'1.18.5'



---



## 배열 생성

### 리스트로 배열 만들기

*인덱스로도 접근 가능


In [4]:
a1 = np.array([1,2,3,4,5])
#list값을 array로 바꾸기
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0])
print(a1[2])

#인덱스로도 접근 가능

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
3


In [5]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
print(a2)
a2.shape
a2[0]
print(a2[0][2])     #차원으로 접근
print(a2[2,1])      #행렬로 접근

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
8


In [7]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [8]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

* `ones()`: 모든 요소를 1로 초기화

In [9]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [10]:
np.full((3,3),1.22)

array([[1.22, 1.22, 1.22],
       [1.22, 1.22, 1.22],
       [1.22, 1.22, 1.22]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [11]:
np.eye((3))[0][0]

1.0

* `tri()`: 삼각행렬 생성

In [12]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [13]:
np.empty(10)

array([2.92143862e-316, 2.14321575e-312, 2.14321575e-312, 8.48798317e-313,
       8.70018275e-313, 1.93101617e-312, 1.97345609e-312, 1.01855798e-312,
       4.59481051e-322, 0.00000000e+000])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [14]:
print(a1)
np.zeros_like(a1)

[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [15]:
print(a2)
np.zeros_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [17]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [19]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [20]:
np.random.random((3,3))

array([[0.78364483, 0.38132976, 0.6705693 ],
       [0.23962143, 0.27292626, 0.78295818],
       [0.42918937, 0.73516107, 0.87956082]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

* 자기장 스핀 표현 가능

In [21]:
np.random.randint(0,2,(3,3))
# up, down 표현할수 있겠다

array([[1, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [22]:
np.random.normal(0,1,(3,3))

array([[-9.94413196e-01,  4.84398466e-01,  6.39799206e-02],
       [ 2.03138239e-01,  4.27293653e-01, -1.64491322e+00],
       [-5.32136491e-04,  4.90233872e-01, -2.84290918e+00]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [23]:
np.random.rand(3,3)

array([[0.92079075, 0.08048105, 0.67464217],
       [0.04599731, 0.94446858, 0.24698362],
       [0.33451899, 0.44472294, 0.16996985]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [24]:
np.random.randn(3,3)

array([[-1.1072215 , -1.27567937,  0.26318009],
       [-1.28562011, -1.22921464, -0.49953061],
       [-1.71171188, -0.14847193, -0.02861369]])

### 표준 데이터 타입

In [25]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [28]:
date = np.array('2020-02-02',dtype=np.datetime64)
date

array('2020-02-02', dtype='datetime64[D]')

In [29]:
date + np.arange(12)
# 각날짜에 계산 가능한 형태로

array(['2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05',
       '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09',
       '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13'],
      dtype='datetime64[D]')

In [30]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [31]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')

datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [32]:
def array_info(array):
    print(array)
    print('ndim',array.ndim)
    print('shape : ', array.shape)      #5개 요소
    print('dtype : ', array.dtype)      #
    print('size : ', array.size)        #요소에 대한 개수
    print('itemsize : ',array.itemsize) #8바이트의 사이즈
    print('nbytes : ', array.nbytes)    #8*5=40
    print('strides : ',array.strides)   #1 2, 3, 4 하나당 8바이트/넘어가는데 8 필요
array_info(a1)

[1 2 3 4 5]
ndim 1
shape :  (5,)
dtype :  int64
size :  5
itemsize :  8
nbytes :  40
strides :  (8,)


In [33]:
array_info(a2)

#1차원에서 2차로 갈때 8*3=24필요

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape :  (3, 3)
dtype :  int64
size :  9
itemsize :  8
nbytes :  72
strides :  (24, 8)


In [34]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim 3
shape :  (3, 3, 3)
dtype :  int64
size :  27
itemsize :  8
nbytes :  216
strides :  (72, 24, 8)


### 인덱싱(Indexing)

In [35]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])

[1 2 3 4 5]
1
3
5


In [36]:
print(a2)
print(a2[0,0])
print(a2[2,1])
print(a2[-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
8
[7 8 9]


In [37]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
[7 8 9]


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [38]:
print(a1)
print(a1[0:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


In [39]:
print(a2)
print(a2[1])
print(a2[1,:])

#인덱스를 [,]가 들어가면 행렬의 좌표로 접근
#인덱스를 [][]로 표현하면 index로 저근

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [40]:
print(a1)
bi = [False, True, True, False,True]
print(a1[bi])

# True만 뽑는다

bi2 = [True,False,True,True,False]
print(a1[bi2])

[1 2 3 4 5]
[2 3 5]
[1 3 4]


In [41]:
print(a2)
b1 = np.random.randint(0,2,(3,3),dtype = bool)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 팬시 인덱싱(Fancy Indedxing)

In [42]:
print(a1)
print([a1[0],a1[2]])
ind = [0,2]

print(a1[ind])
a1[ind].shape

[1 2 3 4 5]
[1, 3]
[1 3]


(2,)

In [43]:
ind2 = np.array([[0,1],[2,0]])
a1[ind2]


array([[1, 2],
       [3, 1]])

In [44]:
row = np.array([0,2])
col = np.array([1,2])
print(a2[[0,2],col])
print('-----------')
print(a2[row,col])
print('-----------')
print(a2[row, :])
print('-----------')
print(a2[:,col])
print('-----------')
print(a2[row,1])
print('-----------')
print(a2[2,col])
print('-----------')
print(a2[row,1:])
print('-----------')
print(a2[1:,col])

[2 9]
-----------
[2 9]
-----------
[[1 2 3]
 [7 8 9]]
-----------
[[2 3]
 [5 6]
 [8 9]]
-----------
[2 8]
-----------
[8 9]
-----------
[[2 3]
 [8 9]]
-----------
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [45]:
print(a1)
b1 = np.insert(a1,0,10)
#(배열,위치(인덱스), 값)
print(b1)
print(a1)
c1 = np.insert(a1,2,10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]
[ 1  2 10  3  4  5]


In [46]:
print(a2)
b2 = np.insert(a2,1,10,axis=0)          #아예 행
print(b2)
c2 = np.insert(a2, 1, 10 ,axis = 1)     # 열로 한 라인자체를 인덱스로 고려하는구나
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [47]:
print(a1)

a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)

a1[:3] = 9
print(a1)

i = np.array([1,3,4])       #펜시 인덱싱
a1[i] = 2
print(a1)

a1[i] = 3
print(a1)

a1[i] += 4
print(a1)

[1 2 3 4 5]
[1 2 3 4 5]
[9 9 9 4 5]
[9 2 9 2 2]
[9 3 9 3 3]
[9 7 9 7 7]


In [48]:
print(a2)
a2[0,0] = 1
a2[1,1]=2
a2[2,2] = 3
a2[0] = 1

print(a2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]


In [49]:
row = np.array([0,1])
col = np.array([1,2])
a2[row,col]= 0
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 3]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [50]:
print(a1)
b1 = np.delete(a1,1)
print(b1)

[9 7 9 7 7]
[9 9 7 7]


In [51]:
print(a2)
b2 = np.delete(a2,1,axis = 0)

print(b2)

c2=np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 3]]
[[1 0 1]
 [7 8 3]]
[[1 1]
 [4 0]
 [7 3]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [52]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)

a2_sub[:,1] = 0
print(a2_sub)
print(a2)


[[1 0 1]
 [4 2 0]
 [7 8 3]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 3]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [53]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()     #복사복은 리턴시켜준거지
print(a2_sub_copy)
a2_sub_copy[:, 1] =1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 3]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 3]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [54]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 0 3]]


In [55]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [56]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 0 3]]


In [57]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))
            #(축,축)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [58]:
n1 = np.arange(1,10)
print(n1)
n1.reshape(3,3)
# 형상을 바꾸는건 reshape

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* `newaxis()`: 새로운 축 추가

In [59]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [60]:
n2 = np.random.randint(0,10,(2,5))
print(n2)

n2.reshape(5,2)         #reshape 는 차원만?
print(n2)               #요소의 합이 항상 같아야함

n2.resize((5,2))        #resize는 배열 모양을?
print(n2)               #크기를 키우거나 줄일수잇음


[[1 9 6 3 0]
 [9 4 0 0 4]]
[[1 9 6 3 0]
 [9 4 0 0 4]]
[[1 9]
 [6 3]
 [0 9]
 [4 0]
 [0 4]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [61]:
n2.resize((5,5))
print(n2)

[[1 9 6 3 0]
 [9 4 0 0 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [62]:
n2.resize((3,3))
print(n2)           #배열 크기를 줄이면 삭제 가능

[[1 9 6]
 [3 0 9]
 [4 0 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [63]:
a2 = np.arange(1,10).reshape(3,3)
b2 = np.arange(10,19).reshape(3,3)
print(a2)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [64]:
c2 = np.append(a2,b2)
print(c2)

# 특정 지정이 없으면 무조건 1차원 형태로 배열됨


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [65]:
c2 = np.append(a2,b2,axis=0)        #축이니까 열로 붙음
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [66]:
c2 = np.append(a2,b2,axis = 1)      #1축이니까 행으로 붙음
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [67]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [68]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [69]:
a2 = np.array([[1,2,3],
               [4,5,6]])

np.concatenate([a2,a2])         #기본적으로 아래에 붙는다

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
a2 = np.array([[1,2,3],
               [4,5,6]])

np.concatenate([a2,a2],axis = 1)        #1축 이니까 당연이 행으로 오겠지

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [71]:
np.vstack([a2,a2])      #verticle stack
                        # 아래로 붙어 like <axis = 0>


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [72]:
np.hstack([a2,a2])     #horizen stack
                        # 옆으로 붙어 like <axis = 1>

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [73]:
print(a2)
np.dstack([a2,a2])

[[1 2 3]
 [4 5 6]]


array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [74]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [75]:
a1 = np.arange(0,10)
print(a1)

b1,c1 = np.split(a1,[5])
print(b1,c1)

b1,c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [76]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [78]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [79]:
a2 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.hsplit(a3,[2])
print(b3)
print(c3 )

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[7 8 9]]

 [[7 8 9]]

 [[7 8 9]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [80]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

#부뤗케스팅!

[1 2 3]
[6 7 8]


In [83]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1)
print(a1+a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [85]:
b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [93]:
a1 = np.arange(1,10)
print(a1)
print(a1+1)
a2 = np.arange(1,10).reshape(9,1)
a3 = np.arange(11,20)
print(a2)
print(a3)
a2+a3           
                    #브뤗케스팅

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[11 12 13 14 15 16 17 18 19]


array([[12, 13, 14, 15, 16, 17, 18, 19, 20],
       [13, 14, 15, 16, 17, 18, 19, 20, 21],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [15, 16, 17, 18, 19, 20, 21, 22, 23],
       [16, 17, 18, 19, 20, 21, 22, 23, 24],
       [17, 18, 19, 20, 21, 22, 23, 24, 25],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [96]:
a1 = np.arange(1,10)
print(a1+1)
print(np.add(a1,1))

[ 2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]


In [103]:
print(np.negative(a1))
print(a1*2)
print(np.multiply(a1,2))
print(a1/2)
print(np.divide(a1,2))
print(np.floor_divide(a1,2))
print(a1%2)

[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[1 0 1 0 1 0 1 0 1]


In [110]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=(9,9))
print(b1)
print(a1+b1)

[1 2 3 4 5 6 7 8 9]
[[3 7 7 9 4 8 3 4 1]
 [8 4 5 6 5 3 6 1 4]
 [4 1 4 1 3 1 6 7 2]
 [1 8 6 1 7 1 6 4 2]
 [2 5 1 1 2 4 8 7 9]
 [2 6 9 9 7 4 3 6 3]
 [3 9 2 5 9 7 7 9 4]
 [5 5 5 3 9 4 7 1 7]
 [3 1 2 8 6 3 4 8 3]]
[[ 4  9 10 13  9 14 10 12 10]
 [ 9  6  8 10 10  9 13  9 13]
 [ 5  3  7  5  8  7 13 15 11]
 [ 2 10  9  5 12  7 13 12 11]
 [ 3  7  4  5  7 10 15 15 18]
 [ 3  8 12 13 12 10 10 14 12]
 [ 4 11  5  9 14 13 14 17 13]
 [ 6  7  8  7 14 10 14  9 16]
 [ 4  3  5 12 11  9 11 16 12]]


In [114]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,(3,3))
print(b2)
print(a2+b2)
print(a2*b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 5]
 [3 2 8]
 [8 2 1]]
[[ 8  6  8]
 [ 7  7 14]
 [15 10 10]]
[[ 7  8 15]
 [12 10 48]
 [56 16  9]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [119]:
a1 = np.random.randint(-10,10,size=5)
print(a1)
print(abs(a1))
print(np.absolute(a1))


[ 6  8  7  9 -8]
[6 8 7 9 8]
[6 8 7 9 8]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [124]:
print(a1)
print(np.square(a1))
np.square(a1)

[ 6  8  7  9 -8]
[36 64 49 81 64]


array([36, 64, 49, 81, 64])

#### 지수와 로그 함수 (Exponential and Log Function)

In [128]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[4 1 6 5 3]
[ 54.59815003   2.71828183 403.42879349 148.4131591   20.08553692]
[16.  2. 64. 32.  8.]
[16  1 36 25  9]


In [129]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[4 1 6 5 3]
[1.38629436 0.         1.79175947 1.60943791 1.09861229]
[2.         0.         2.5849625  2.32192809 1.5849625 ]
[0.60205999 0.         0.77815125 0.69897    0.47712125]


#### 삼각 함수(Trigonometrical Function)


In [132]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [134]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))


[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [136]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(a2.sum(),np.sum(a2))
print(a2.sum(axis=0))           #세로끼리 더하고
print(a2.sum(axis=1))           #가로끼리 더하고

[[1 2 6]
 [5 1 9]
 [4 8 6]]
42 42
[10 11 21]
[ 9 15 18]


#### cumsum(): 누적합 계산

In [140]:

print(a2)
print(np.cumsum(a2))

print(a2.cumsum(axis=0))           #세로끼리 더하고
# print(a2.sum(axis=1)) 

[[1 2 6]
 [5 1 9]
 [4 8 6]]
[ 1  3  9 14 15 24 28 36 42]
[[ 1  2  6]
 [ 6  3 15]
 [10 11 21]]


#### diff(): 차분 계산

In [144]:
print(a2)
print(np.diff(a2)) 
#건너 뛴 값

print(np.diff(a2,axis=0))
print(np.diff(a2,axis=1))   

[[1 2 6]
 [5 1 9]
 [4 8 6]]
[[ 1  4]
 [-4  8]
 [ 4 -2]]
[[ 4 -1  3]
 [-1  7 -3]]
[[ 1  4]
 [-4  8]
 [ 4 -2]]


#### prod(): 곱 계산

In [145]:
print(a2)
print(np.prod(a2)) 


print(np.prod(a2,axis=0))
print(np.prod(a2,axis=1)) 

[[1 2 6]
 [5 1 9]
 [4 8 6]]
103680
[ 20  16 324]
[ 12  45 192]


#### cumprod(): 누적곱 계산

In [146]:
print(a2)
print(np.cumprod(a2)) 


print(np.cumprod(a2,axis=0))
print(np.cumprod(a2,axis=1)) 

[[1 2 6]
 [5 1 9]
 [4 8 6]]
[     1      2     12     60     60    540   2160  17280 103680]
[[  1   2   6]
 [  5   2  54]
 [ 20  16 324]]
[[  1   2  12]
 [  5   5  45]
 [  4  32 192]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [149]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))


[[1 2 6]
 [5 1 9]
 [4 8 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 9  9  9]
 [15 15 15]
 [18 18 18]]


#### tensordot(): 텐서곱 계산

In [152]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))

print(np.tensordot(a2,b2,axes = 0))


[[1 2 6]
 [5 1 9]
 [4 8 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
42
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]


 [[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]]


#### cross(): 벡터곱

In [153]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [154]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[1 2 6]
 [5 1 9]
 [4 8 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 9  9  9]
 [15 15 15]
 [18 18 18]]
[[1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2]
 [6 6 6 6 6 6 6 6 6]
 [5 5 5 5 5 5 5 5 5]
 [1 1 1 1 1 1 1 1 1]
 [9 9 9 9 9 9 9 9 9]
 [4 4 4 4 4 4 4 4 4]
 [8 8 8 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 6 6]]


#### mean(): 평균 계산

In [155]:
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))

[[1 2 6]
 [5 1 9]
 [4 8 6]]
4.666666666666667
[3.33333333 3.66666667 7.        ]
[3. 5. 6.]


#### std(): 표준 편차 계산

In [158]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std (a2,axis=1))

[[1 2 6]
 [5 1 9]
 [4 8 6]]
2.7487370837451066
[1.69967317 3.09120617 1.41421356]
[2.1602469  3.26598632 1.63299316]


#### var(): 분산 계산

In [159]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))

[[1 2 6]
 [5 1 9]
 [4 8 6]]
1
[1 1 6]
[1 1 4]


#### min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))

#### max(): 최대값

In [161]:
print(a2)
print(np.max(a2))
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[[1 2 6]
 [5 1 9]
 [4 8 6]]
9
[5 8 9]
[6 9 8]


#### argmin(): 최소값 인덱스

In [163]:
print(a2)
print(np.argmin(a2))    
print(np.argmin(a2,axis=0))
print(np.argmin(a2,axis=1))
        #인덱스로 출력값을 가져오지

[[1 2 6]
 [5 1 9]
 [4 8 6]]
0
[0 1 0]
[0 1 0]


#### argmax(): 최대값 인덱스

In [164]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))

[[1 2 6]
 [5 1 9]
 [4 8 6]]
5
[1 2 1]
[2 2 1]


#### median(): 중앙값

In [165]:
print(a2)
print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))     #가지고 있는 축의 요소들중에 가운뎃값!

[[1 2 6]
 [5 1 9]
 [4 8 6]]
5.0
[4. 2. 6.]
[2. 5. 6.]


#### percentile(): 백분위 수



In [168]:
a1= np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [169]:
a2 = np.array([[False,False,False],
               [False,True,True],
               [False,True,True]])

print(a2)
print(np.any(a2))               
    # 이중에 하나라도 true면 ture임

print(np.any(a2,axis=0))
    #axis = 0이면 세로
print(np.any(a2,axis=1))
    #axis = 0이면 가로

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [171]:
a2 = np.array([[False,False,True],
               [False,True,True],
               [False,True,True]])

print(a2)
print(np.all(a2))               
    # 이중에 하나라도 False면 False임

print(np.all(a2,axis=0))
    #axis = 0이면 세로
print(np.all(a2,axis=1))
    #axis = 0이면 가로

[[False False  True]
 [False  True  True]
 [False  True  True]]
False
[False False  True]
[False False False]


### 비교 연산(Comparison Operators)


In [176]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1<=5)
print(a1>=5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True  True False False False False]
[False False False False  True  True  True  True  True]


In [184]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2 > 5))
    #w이렇게 조건도 붙일수 잇음

print(np.sum(a2 > 5,axis=0))

print(np.sum(a2 > 5,axis=1))

print(np.any(a2 > 5 , axis =1))

print(np.all(a2 >5 , axis =1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
[False  True  True]
[False False  True]


In [188]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1))

# 3과 4 , 5와4의 거리가 있으니까 false나온거

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [192]:
s1 = np.array([np.nan,2,np.inf,4,np.NINF])
print(s1)
print(np.isnan(s1))
print(np.isinf(s1))
print(np.isfinite(s1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [200]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

print((a2 >5) & (a2 <8))
#조건이 맞으면 True, 아니면 False
#       and라는 뜻
print(a2[(a2 >5) & (a2 <8)])
# 6번 7번이 True니까 인덱스 6,7번이 나옴

print((a2 >5) | (a2 <8))
print(a2[(a2 >5) | (a2 <8)])
#       or 이라는 뜻

print((a2 >5) ^ (a2 <8))
print(a2[(a2 >5) ^ (a2 <8)])
#xor


print(~(a2 >5))
print(a2[~(a2 >5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [204]:
a1 = np.random.randint(1,10,10)
print(a1)
print(np.sort(a1))
print(a1)           #d원본 배열은 그대로
print(np.argsort(a1))   #인덱스값을 가져옴
print(a1)
print(a1.sort())
print(a1)

[7 4 9 6 3 4 4 7 6 5]
[3 4 4 4 5 6 6 7 7 9]
[7 4 9 6 3 4 4 7 6 5]
[4 1 5 6 9 3 8 0 7 2]
[7 4 9 6 3 4 4 7 6 5]
None
[3 4 4 4 5 6 6 7 7 9]


In [206]:
a2 = np.random.randint(1,10,(3,3))
print(a2)
print(np.sort(a2, axis=0))      #세로!
print(np.sort(a2, axis=1))      #가로!


[[6 5 9]
 [8 8 9]
 [7 6 5]]
[[6 5 5]
 [7 6 9]
 [8 8 9]]
[[5 6 9]
 [8 8 9]
 [5 6 7]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [207]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))
#이중에 작은 값 3개 뽑아줘!


[3 7 1 3 3 3 4 8 7 7]
[3 3 1 3 7 3 4 8 7 7]


In [209]:
a2 = np.random.randint(1,10,(5,5))
print(a2)
print(np.partition(a2,3, axis=0))
print(np.partition(a2,3, axis=1))

[[4 8 8 8 5]
 [8 5 6 8 5]
 [4 2 4 9 8]
 [7 1 4 8 2]
 [2 4 4 9 3]]
[[2 1 4 8 2]
 [4 2 4 8 3]
 [4 4 4 8 5]
 [7 5 6 9 5]
 [8 8 8 9 8]]
[[4 5 8 8 8]
 [5 5 6 8 8]
 [2 4 4 8 9]
 [1 2 4 7 8]
 [2 3 4 4 9]]


## 배열 입출력


In [211]:
#배열을 만든걸 저장하려고
# np.save()
# np.savez()
# np.load()
# np.loadtxt()
# np.savetxt()
a2 = np.random.randint(1,10,(5,5))
print(a2)
np.save('a',a2)

[[9 3 1 8 2]
 [9 6 6 6 1]
 [6 2 1 7 7]
 [4 7 8 5 6]
 [6 8 8 6 5]]


In [212]:
!ls
#np에서 저장한 바이너리 file

a.npy  sample_data


In [213]:
b2 = np.random.randint(1,10,(5,5))
print(b2)
np.savez('ab',a2,b2)

[[3 2 9 3 1]
 [5 4 4 4 8]
 [2 3 7 2 1]
 [7 8 7 6 1]
 [3 3 2 1 3]]


In [214]:
!ls
#저장이 잘 됐는지
#확장자가 npz로 됐네 여러갠건가

ab.npz	a.npy  sample_data


In [216]:
npy = np.load('a.npy')
print(npy)

#a.npy를 불러줘! 그리고 npy에 할당해줘!

[[9 3 1 8 2]
 [9 6 6 6 1]
 [6 2 1 7 7]
 [4 7 8 5 6]
 [6 8 8 6 5]]


In [217]:
npz = np.load('ab.npz')
print(npz.files)
#불러오는건 똑같고 files를 붙여준다

['arr_0', 'arr_1']


In [219]:
#이때 접근을 따로 할수있다
print(npz['arr_0'])
print(npz['arr_1'])

[[9 3 1 8 2]
 [9 6 6 6 1]
 [6 2 1 7 7]
 [4 7 8 5 6]
 [6 8 8 6 5]]
[[3 2 9 3 1]
 [5 4 4 4 8]
 [2 3 7 2 1]
 [7 8 7 6 1]
 [3 3 2 1 3]]


In [220]:
print(a2)
#아냐 나는 텍스트로 저장하고 싶어
np.savetxt('a.csv',a2,delimiter=',')
# 텍스트로 저장하면 사람이 읽을수있는게 되지

[[9 3 1 8 2]
 [9 6 6 6 1]
 [6 2 1 7 7]
 [4 7 8 5 6]
 [6 8 8 6 5]]


In [221]:
!ls
#a.csv 파일ㅇ ㅣ생겼구만!

ab.npz	a.csv  a.npy  sample_data


In [222]:
!cat a.csv
#텍스트로 저장했으니까 바로 볼수 있지
#실수형태로
#왜냐면 텍스트 형태로 저장하기때문에 데이터 타입까지는 저장을 못한거지

9.000000000000000000e+00,3.000000000000000000e+00,1.000000000000000000e+00,8.000000000000000000e+00,2.000000000000000000e+00
9.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,1.000000000000000000e+00
6.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00,7.000000000000000000e+00,7.000000000000000000e+00
4.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00
6.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00,6.000000000000000000e+00,5.000000000000000000e+00


In [223]:
csv = np.loadtxt('a.csv',delimiter=',')
#   delimiter은 구분자임  보통 ,로 하면 csv 형식이 되지

In [224]:
print(csv)

[[9. 3. 1. 8. 2.]
 [9. 6. 6. 6. 1.]
 [6. 2. 1. 7. 7.]
 [4. 7. 8. 5. 6.]
 [6. 8. 8. 6. 5.]]


In [226]:
print(b2)
np.savetxt('b.csv',b2,delimiter=',',fmt='%.2e',header = 'c1,c2,c3,c4,c5')
                                    #소숫점 관리 가능

[[3 2 9 3 1]
 [5 4 4 4 8]
 [2 3 7 2 1]
 [7 8 7 6 1]
 [3 3 2 1 3]]


In [227]:
!cat b.csv
#소수점 2자리까지만 읽어왔네

# c1,c2,c3,c4,c5
3.00e+00,2.00e+00,9.00e+00,3.00e+00,1.00e+00
5.00e+00,4.00e+00,4.00e+00,4.00e+00,8.00e+00
2.00e+00,3.00e+00,7.00e+00,2.00e+00,1.00e+00
7.00e+00,8.00e+00,7.00e+00,6.00e+00,1.00e+00
3.00e+00,3.00e+00,2.00e+00,1.00e+00,3.00e+00


In [228]:
csv = np.loadtxt('b.csv',delimiter=',')
print(csv)

[[3. 2. 9. 3. 1.]
 [5. 4. 4. 4. 8.]
 [2. 3. 7. 2. 1.]
 [7. 8. 7. 6. 1.]
 [3. 3. 2. 1. 3.]]


In [ ]:
#numpy.org ->Documentation
#으로 들어가면 최신 업데이트를 볼수잇음



---

