In [1]:
import numpy as np

In [2]:
# 모두 0으로 채운 3 x 3 배열 a 생성 
a = np.zeros((3,3))
print(a)

# 모두 1로 채운 2 x 3 배열 b 생성
b = np.ones((2,3))
print(b)

# 5로 채운 2 x 3 x 3 배열 c 생성
c = np.ones((2,3,3))+np.ones((2,3,3))+np.ones((2,3,3))+np.ones((2,3,3))+np.ones((2,3,3))
print(c)

# 5 x 5 단위 행렬 d 생성
d = np.eye(5)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
# range, reshape 함수를 사용하여 1~20 의 정수로 4 x 5 배열 arr 생성
g = np.arange(1,21).reshape(4,5)
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
# 불린 인덱스를 이용하여 arr 배열의 대각선 '\' 상의 요소 선택
m = [[True,False,False],
    [False,True,False],
    [False,False,True]]

m2 = [True,False,False]

arr = np.random.randint(1,20,(3,3))
# b1 = np.random.randint(0,2,(3,3),dtype = bool)
b2 = np.array([[1,0,0],[0,1,0],[0,0,1]], dtype = bool)
print(arr)
print(arr[b2])
# print(arr[m2])
# arr[m2]
# arr[m]

[[ 2  8 19]
 [11 15  2]
 [14 10  4]]
[ 2 15  4]


In [55]:
# arr 배열의 인덱스가 짝수인 요소만 조회 (불린 인덱스와 조건식을 조합)
a2 = np.random.randint(1,10,10)
print(a2)
for i in range(5):
    a2[2*i] = True

t = []

for j in range(len(a2)):
    if a2[j] is True:
        append.t(a2[j])

t


[2 8 1 5 1 6 7 7 1 3]


[]

# 배열 간 연산

In [6]:
m1 = np.array([
    [1,2],
    [3,4]
])
m2 = np.array([
    [5,6],
    [7,8]
])

# m1, m2 배열의 각 요소 간 합, 차, 곱 그리고 행렬곱을 구하기
print(m1 + m2)
print(m1-m2)
print(m1*m2)
print(m1.dot(m2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [7]:
# arr 배열의 컬럼(열)별 합계
# print(sum(m1[0]))
# print(sum(m1[1]))
print(m1)
print(np.sum(m1,axis = 0))
# print(np.sum(m1, axis = 1))

[[1 2]
 [3 4]]
[4 6]


In [8]:
# arr 배열의 행별 평균
# print(np.mean(m1,axis = 0))
print(m1)
print(np.mean(m1,axis =1))

[[1 2]
 [3 4]]
[1.5 3.5]


## 구글 드라이브와 연동하여 파일을 불러오기 해 보겠습니다.

In [9]:
# 아래 코드를 실행하세요

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


다음과 같은 실행 결과가 나오면 URL을 클릭하세요.

그럼 아래와 같은 페이지가 뜰거에요.

![alt text](https://t1.daumcdn.net/cfile/tistory/99AE13495BECEC180F)


[허용] 버튼을 클릭하시면 인증 코드가 나와요. 코드를 복사하셔서 authorization code: 영역에 붙여 넣기 하시면 됩니다.

이제부터는 /content/gdrive/My Drive/Colab Notebooks/data/ 경로에 업로드한 파일을 colab에서 불러와서 사용할 수 있습니다.

(data 폴더는 따로 만들었어요. 여기에 외부 데이터 파일을 모아 두세요.)




In [11]:
import pandas as pd
# 아래 코드를 실행하여 cars 데이터셋을 불러오기 하세요.

# dat = np.genfromtxt("/content/drive/My Drive/data/cars.txt", skip_header=True)
dat = pd.read_csv('/content/drive/My Drive/data/박성흠 - cars.csv')
dat

speed dist
0         4 2
1        4 10
2         7 4
3        7 22
4        8 16
5        9 10
6       10 18
7       10 26
8       10 34
9       11 17
10      11 28
11      12 14
12      12 20
13      12 24
14      12 28
15      13 26
16      13 34
17      13 34
18      13 46
19      14 26
20      14 36
21      14 60
22      14 80
23      15 20
24      15 26
25      15 54
26      16 32
27      16 40
28      17 32
29      17 40
30      17 50
31      18 42
32      18 56
33      18 76
34      18 84
35      19 36
36      19 46
37      19 68
38      20 32
39      20 48
40      20 52
41      20 56
42      20 64
43      22 66
44      23 54
45      24 70
46      24 92
47      24 93
48     24 120
49      25 85

In [12]:
# dat 데이터에서 첫번째열은 speed, 두번째열은 dist입니다. speed 데이터만 추출하여 speed 변수에 저장하세요.

speed = [ ]
dist = []
a = str(dat.iloc[:,0]).split()
# print(a)

del a [::3]
# print(a)
del a[-3:]
# print(a)
# for i in range(40):
#     del a[3*i]
for i in range(41):
    speed.append(a[2*i])
    dist.append(a[2*i+1])
# print(len(a))
# print(a)
print(speed)
print(dist)

['4', '4', '7', '7', '8', '9', '10', '10', '10', '11', '11', '12', '12', '12', '12', '13', '13', '13', '13', '14', '14', '14', '14', '15', '15', '15', '16', '16', '17', '17', '17', '18', '18', '18', '18', '19', '19', '19', '20', '20', '20']
['2', '10', '4', '22', '16', '10', '18', '26', '34', '17', '28', '14', '20', '24', '28', '26', '34', '34', '46', '26', '36', '60', '80', '20', '26', '54', '32', '40', '32', '40', '50', '42', '56', '76', '84', '36', '46', '68', '32', '48', '52']


In [21]:
# speed 의 평균, 분산을 구하세요.
import numpy as np


speed = list(map(int,speed))                #숫자로 보이지만 문자열이엿음
speed_array = np.array(speed)
# np.mean(speed_array)
# np.var(speed_array)
# .astype(np.int64)
print(np.mean(speed_array))
print(np.var(speed_array))

13.75609756097561
17.745389649018442
